apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-backend
  template:
    metadata:
      labels:
        app: student-backend
    spec:
      containers:
        - name: student-backend
          image: varshini89211/student-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "mysql"       # Kubernetes service name
            - name: DB_USER
              value: "root"
            - name: DB_PASS
              value: "Varshini@747"
            - name: DB_NAME
              value: "students_db"
