apiVersion: v1
kind: Service
metadata:
  name: student-backend-service
spec:
  type: NodePort
  selector:
    app: student-backend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001
